# 卒業研究用のワークフロー
name: Run Tests and Process Results

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Write consoleTransrate config
        run: |
          mkdir -p ~/.consoleTransrate
          echo ${{ secrets.CONFIG_JSON }} > ~/.consoleTransrate/config.json

      - name: Run Jest tests
        run: npm test --outputFile=jest-results.json
      - name: Upload Jest Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: jest-results.json

      - name: Process Jest Test Results
        uses: kamesan1577/ci-gamificator@v0.7
        with:
          artifact-name: "jest-results"
